apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vsphere-cred
  namespace: default
  labels:
    cluster.open-cluster-management.io/type: vmw
    cluster.open-cluster-management.io/credentials: ""
stringData:
  vCenter: X
  username: X
  password: X
  cacertificate: X
  cluster: X
  datacenter: X
  defaultDatastore: vsanDatastore
  vsphereFolder: ""
  vsphereResourcePool: ""
  vsphereDiskType: ""
  baseDomain: X
  pullSecret: X
  ssh-privatekey: X
  ssh-publickey: X
  imageContentSources: ""
  disconnectedAdditionalTrustBundle: ""
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  additionalTrustBundle: ""
