name: Build Container Image

on: pull_request

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Oded 1234"
      - name: multiline script
        run: |
          node -v
          npm -v
